### ISSUE TITLE
Add GitHub workflow for publishing packages

### ISSUE THREAD

**Issue by MthwRobinson** [civic-jabber/data-ingest#15]
There should be a GitHub Actions workflow that publishes a package to PyPI whenever create a new tag. This will also required created a PyPI account for the Civic Jabber project and adding the credentials to the list of secrets in GH.

**Comment by kvnkho** [comment]
I can definitely do this and also add a build target to the Makefile. I am kinda hesitant to own the associated PyPi account though. Can you be the one to create the account and give me the credentials?

**Comment by MthwRobinson** [comment]
Yep that sounds good. If I add the credentials as a secret you should be able to hook into that in GH Actions. As part of this, may also be worth switching the packaged name from `data_ingest` to `civic_jabber_ingest` or something like that. Oddly, `data_ingest` doesn't look like it's taken, but figure it's better to be specific.

I'll get the PyPI acount set up later this week.

**Comment by MthwRobinson** [comment]
@kvnkho -- Just added the PyPI creds as org secrets. The username is under `PYPI_USERNAME` and the password is under `PYPI_PASSWORD`. You should be able to hook into those in the GHA workflow.

**Comment by kvnkho** [comment]
Perfect will get this done today.
